name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout master
#        uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.17.7
#
#      - name: Run Tests
#        run: go test ./...
#
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout master
#        uses: actions/checkout@v3
#
#      - name: Run Lints
#        uses: golangci/golangci-lint-action@v3
#        with:
#          version: v1.49

  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.7

      - name: make test
        run: make test

      - name: make lint
        run: make lint
