name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Go 1.17.7
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.7

      - name: Test
        run: go test ./...

      - name: Lint
        run: golangci-lint run