name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Go 1.17.7
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.7

      - name: Run Tests
        run: go test ./...

      - name: Run Lints
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49